# -*- coding: utf-8 -*-
"""shopify_exploratory_data_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6NauzrkHFQce_wVhRLFfNHkYZAb7XOK

# Exploratory Data Analysis using Pandas, Matplotlib, Seaborn, and Numpy by Python

---

## DataX Labs Internship — Day 5

Author: **Lord Davon Mendoza**

Task: Use Python to conduct EDA

Tools: Python(Google Colab)

## **1. Setup**
"""

# Import libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

"""## **2. Load the Data**"""

# Load the dataset
df = pd.read_csv("shopify_sales.csv")
df

"""## **3. Explore Data**"""

# View the table summary
df.head()

df.tail()

# Display table info
df.info()

# Display the table in high-level
df.describe()

"""## **4. Check for Issues**"""

# Check the datatypes of each column
df.dtypes

# Check for null values
df.isnull().sum()

# Check unique values
df.nunique()

# Check for duplicate values
df.duplicated().sum()

# It was detected that the order date column was in a string format

# Convert order date into DATE format
df['order_date'] = pd.to_datetime(df['order_date'])
df.dtypes

# Set the decimal space
pd.set_option('display.float_format', lambda x: '%.2f' % x)

"""## **5. Visualizations**"""



"""### A. **Correlation Matrix**"""

# View the correlation between columns

id_cols = ['order_id', 'customer_id', 'product_id']

numeric_df = df.drop(columns=id_cols).select_dtypes(include='number')

corr = numeric_df.corr()

# Visualize the correlation as a heatmap

mask = np.triu(np.ones_like(corr, dtype=bool))

plt.figure(figsize=(10, 8))
sns.heatmap(
    corr,
    mask=mask,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0,
    square=True,
    linewidths=.5,
    cbar_kws={'shrink': .8, 'label': 'Correlation Coefficient'}
)
plt.title('Correlation Matrix of Numeric Features', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""### **B. Monthly and Quarterly Sales per Country**"""

# Ensure 'order_date' is datetime type
if not pd.api.types.is_datetime64_any_dtype(df['order_date']):
    df['order_date'] = pd.to_datetime(df['order_date'])

# Monthly Sales Per Country Over Time

# Extract year-month for monthly aggregation
df['year_month'] = df['order_date'].dt.to_period('M')

# Aggregate monthly revenue by country
monthly_sales_country = df.groupby(['year_month', 'customer_country'])['revenue'].sum().reset_index()
monthly_sales_country['year_month'] = monthly_sales_country['year_month'].astype(str) # Convert to string for plotting

# Plot Monthly Sales by Country
plt.figure(figsize=(18, 9)) # Increased figure size for more lines
sns.lineplot(data=monthly_sales_country, x='year_month', y='revenue', hue='customer_country', marker='o')
plt.title('Monthly Sales Per Country Over Time', fontsize=16)
plt.xlabel('Month', fontsize=12)
plt.ylabel('Total Sales ($)', fontsize=12)
plt.xticks(rotation=60, ha='right')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Country')
plt.tight_layout()
plt.show()

# Quarterly Sales Per Country Over Time

# Extract year-quarter for quarterly aggregation
df['year_quarter'] = df['order_date'].dt.to_period('Q')

# Aggregate quarterly revenue by country
quarterly_sales_country = df.groupby(['year_quarter', 'customer_country'])['revenue'].sum().reset_index()
quarterly_sales_country['year_quarter'] = quarterly_sales_country['year_quarter'].astype(str) # Convert to string for plotting

# Plot Quarterly Sales by Country
plt.figure(figsize=(15, 8)) # Increased figure size
sns.lineplot(data=quarterly_sales_country, x='year_quarter', y='revenue', hue='customer_country', marker='o')
plt.title('Quarterly Sales Per Country Over Time', fontsize=16)
plt.xlabel('Quarter', fontsize=12)
plt.ylabel('Total Sales ($)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Country')
plt.tight_layout()
plt.show()

"""### **C. Total Revenue and Profit by Product Categories**"""

# Group by product category and sum revenue
revenue_by_category = df.groupby('product_category')['revenue'].sum().sort_values(ascending=False).reset_index()

# Define custom colors: 'darkblue' for Electronics, 'lightsteelblue' for others
colors = ['darkblue' if category == 'Electronics' else 'lightsteelblue' for category in revenue_by_category['product_category']]

# Create the bar chart with custom colors
plt.figure(figsize=(12, 6))
sns.barplot(x='product_category', y='revenue', data=revenue_by_category, palette=colors)
plt.title('Total Revenue by Product Category', fontsize=16)
plt.xlabel('Product Category', fontsize=12)
plt.ylabel('Total Revenue ($)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Group by product category and sum profit
profit_by_category = df.groupby('product_category')['profit'].sum().sort_values(ascending=False).reset_index()

# Define custom colors: 'darkblue' for Electronics, 'lightsteelblue' for others
colors = ['darkblue' if category == 'Electronics' else 'lightsteelblue' for category in profit_by_category['product_category']]

# Create the bar chart with custom colors
plt.figure(figsize=(12, 6))
sns.barplot(x='product_category', y='profit', data=profit_by_category, palette=colors, hue='product_category', legend=False)
plt.title('Total Profit by Product Category', fontsize=16)
plt.xlabel('Product Category', fontsize=12)
plt.ylabel('Total Profit ($)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

def bucket_discount(pct):
    if pct == 0:
        return 'No discount (0%)'
    elif pct <= 15:
        return 'Low (5-15%)'
    else:
        return 'High (20%+)'

df['discount_bucket'] = df['discount_percent'].apply(bucket_discount)
bucket_order = ['No discount (0%)', 'Low (5-15%)', 'High (20%+)']
df['discount_bucket'] = pd.Categorical(df['discount_bucket'], categories=bucket_order, ordered=True)

# Average profit per order, by discount bucket and product category.
# Using the mean (not sum) answers "does a discounted order tend to
# be less profitable", independent of how many orders fall in each
# bucket -- a sum would just reflect order counts, not discount impact.
profit_by_bucket = (
    df.groupby(['discount_bucket', 'product_category'], observed=True)['profit']
    .mean()
    .reset_index()
)

fig, ax = plt.subplots(figsize=(11, 6))
sns.barplot(
    data=profit_by_bucket,
    x='product_category',
    y='profit',
    hue='discount_bucket',
    hue_order=bucket_order,
    ax=ax
)
ax.set_title('Average profit per order, by discount level and category', fontsize=13, pad=12)
ax.set_xlabel('Product category')
ax.set_ylabel('Average profit per order ($)')
ax.legend(title='Discount level')
plt.xticks(rotation=15)
plt.tight_layout()